# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 493f461e0b0f94f647d19b98fe1ef9f85681d8274f6b20c9f2bacfb2cbf6c26b1e597ffd8629e63a494ce8ebb678ffaff1a979da41fad8e67c80e9836504790a

test:
  secret_key_base: d58274c561dc7a8f9191128414d7001f6a3e800e942966cdf3617caa905ce1670ad29a17bccd2eeaa17a0181a93e50ebdf3a595c6925d322b31810224e40835d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
